import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "../components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scripts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
        <Toaster
          className="font-[700]"
          toastOptions={{
            duration: 4000,
            style: {
              background: "rgb(209 213 219)",
              color: "black",
              fontSize: "15px",
              fontWeight: "700",
            },
          }}
        />
        <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
